version: '3.5'
services:
  postgres:
    container_name: us_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: us_db
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
       - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local